import assert from 'node:assert/strict';
import { formatEvidenceCurrency, parseCanonicalEvidence, partisanMarginLabel } from './canonicalEvidence.js';

const source = { sourceId: 'official', sourceUrl: 'https://www.fec.gov/data/candidate/H0CA00001/', retrievedAt: '2026-07-31T00:00:00Z', sourceVintage: '2026-Q2', methodology: 'Official test evidence.' };
const research = { baselineResearch: { fields: { identity: { availability: 'present', value: { fecCandidateId: 'H0CA00001' }, ...source }, filing: { availability: 'present', value: { fecCandidateId: 'H0CA00001' }, ...source } } }, fecFinance: { availability: 'present', cycle: 2026, filingPeriod: '2026-06-30', values: { totalReceipts: 100, totalDisbursements: 50, cashOnHand: 50, debtsOwed: 0 }, ...source }, congressDepth: { availability: 'present', bioguideId: 'A000001', profile: { officialName: 'Alex Example', chamber: 'House', state: 'CA', sourceUrl: 'https://api.congress.gov/v3/member/A000001', retrievedAt: '2026-07-31T00:00:00Z' }, sponsored: [{ identifier: 'HR 1', title: 'Example Act', sourceUrl: 'https://api.congress.gov/v3/bill/119/hr/1' }], cosponsored: [], votes: [{ chamber: 'House', rollNumber: 1, date: '2026-01-01', title: 'Example vote', vote: 'Yea', sourceUrl: 'https://clerk.house.gov/Votes/20261' }], methodology: 'Official records.' } };
const metrics = { historical: { availability: 'present', electionYear: 2024, totalVotes: 1000, marginPct: -2.5, ...source }, turnout: { availability: 'present', turnoutProxy: 0.61, votes: 610, cvapEstimate: 1000, ...source }, demographics: { availability: 'present', cvapEstimate: 1000, geography: 'congressional-district', estimateVintage: 2024, ...source } };
const view = parseCanonicalEvidence(research, metrics); assert.equal(view.identity.availability, 'present'); assert.equal(view.finance.debtsOwed, 0); assert.equal(view.congress.sponsored.length, 1); assert.equal(view.congress.votes.length, 1); assert.equal(view.historical.marginPct, -2.5); assert.equal(view.turnout.turnoutProxy, 0.61); assert.equal(view.cvap.cvapEstimate, 1000); assert.deepEqual(view.issues, []);
assert.equal(partisanMarginLabel(-2.5), 'R+2.5'); assert.equal(partisanMarginLabel(0), 'Even'); assert.match(formatEvidenceCurrency(0), /\$0/);
const malformed = parseCanonicalEvidence({ fecFinance: { availability: 'present', values: {} }, congressDepth: { availability: 'present', sponsored: [{ nope: true }], cosponsored: [], votes: [] } }, 'bad'); assert.equal(malformed.finance.availability, 'unavailable'); assert.ok(malformed.issues.length >= 2);
const missing = parseCanonicalEvidence(null, null); assert.equal(missing.identity.availability, 'unavailable'); assert.equal(missing.historical.availability, 'unavailable');
console.log('canonical evidence parsing tests passed');
