import { expect, test } from '@playwright/test';

test('2026/live is the browser default and closed picks are disabled', async ({ page }) => {
  await page.goto('/?browser-test=active-cycle');
  await expect(page.getByRole('heading', { name: '2026 Live Races' })).toBeVisible();
  await expect(page.getByText('Picks lock before Election Day under the current league safety policy.')).toBeVisible();
  await expect(page.getByText(/official state poll closing/i)).toHaveCount(0);
  await expect(page.getByTestId('race-2026-CA-senate-class-1')).toBeVisible();
  await expect(page.getByTestId('race-2026-CA-senate')).toHaveCount(0);
  await expect(page.getByTestId('race-2026-CA-governor')).toBeVisible();
  await expect(page.getByTestId('measure-browser-measure-2026')).toBeVisible();
  await expect(page.getByTestId('measure-source-browser-measure-2026')).toContainText('on_ballot');
  await expect(page.getByTestId('pick-measure-browser-measure-2026')).toBeEnabled();
  await page.getByTestId('pick-measure-browser-measure-2026').click();
  await expect(page.getByTestId('pick-measure-browser-measure-2026')).toContainText('Pick recorded');
  await expect(page.getByTestId('picks-unavailable-browser-measure-catalog-only')).toContainText('Picks not yet available');
  await expect(page.getByTestId('pick-measure-browser-measure-catalog-only')).toBeDisabled();
  await expect(page.getByTestId('canonical-evidence').first()).toContainText('Campaign finance');
  await expect(page.getByTestId('finance-evidence').first()).toContainText('$1,250,000');
  await expect(page.getByTestId('finance-evidence').first()).toContainText('Financial context, not a forecast.');
  await expect(page.getByTestId('historical-evidence').first()).toContainText('R+2.5');
  await expect(page.getByTestId('turnout-evidence').first()).toContainText('61.0%');
  await expect(page.getByTestId('cvap-evidence').first()).toContainText('538,816');
  await expect(page.getByTestId('congress-evidence').first()).toContainText('Official Example Act');
  await expect(page.getByTestId('unavailable-evidence')).toContainText('FEC totals are unavailable.');
  await expect(page.getByTestId('unavailable-evidence')).toContainText('Official source could not be validated.');
  await expect(page.getByTestId('picks-unavailable-2026-CA-senate-class-1')).toContainText('Picks not yet available');
  await expect(page.getByTestId('pick-fec-canonical')).toContainText('Picks not yet available');
  await expect(page.getByTestId('pick-fec-canonical')).toBeDisabled();
  await expect(page.getByTestId('race-2026-GA-senate-class-2')).toBeVisible();
  await expect(page.getByTestId('picks-unavailable-2026-GA-senate-class-2')).toBeVisible();
  await expect(page.getByTestId('race-2026-GA-senate-class-2').getByRole('button')).toBeDisabled();
  await expect(page.getByTestId('race-2026-VA-house-001')).toBeVisible();
  await expect(page.getByTestId('race-2026-VA-house-001').getByRole('button')).toContainText('Make pick');
  await page.getByTestId('race-2026-VA-house-001').getByRole('button').click();
  await expect(page.getByTestId('race-2026-VA-house-001').getByRole('button')).toContainText('Pick recorded');
  await expect(page.getByTestId('race-browser-closed-2026')).toContainText('Picking closed');
  await expect(page.getByTestId('race-browser-closed-2026').getByRole('button')).toBeDisabled();
  await expect(page.getByTestId('race-fixture-race-2024-sandbox')).toHaveCount(0);
});
