import { expect, test } from '@playwright/test';

test('2026/live is the browser default and closed picks are disabled', async ({ page }) => {
  await page.goto('/?browser-test=active-cycle');
  await expect(page.getByRole('heading', { name: '2026 Live Races' })).toBeVisible();
  await expect(page.getByText('Picks lock before Election Day under the current league safety policy.')).toBeVisible();
  await expect(page.getByText(/official state poll closing/i)).toHaveCount(0);
  await expect(page.getByTestId('race-2026-CA-senate-class-1')).toBeVisible();
  await expect(page.getByTestId('race-2026-CA-senate')).toHaveCount(0);
  await expect(page.getByTestId('race-2026-CA-governor')).toBeVisible();
  await expect(page.getByTestId('measure-browser-measure-2026')).toBeVisible();
  await expect(page.getByTestId('measure-source-browser-measure-2026')).toContainText('on_ballot');
  await expect(page.getByTestId('pick-measure-browser-measure-2026')).toBeEnabled();
  await page.getByTestId('pick-measure-browser-measure-2026').click();
  await expect(page.getByTestId('pick-measure-browser-measure-2026')).toContainText('Pick recorded');
  await expect(page.getByTestId('picks-unavailable-browser-measure-catalog-only')).toContainText('Picks unavailable');
  await expect(page.getByTestId('pick-measure-browser-measure-catalog-only')).toBeDisabled();
  await expect(page.getByTestId('canonical-evidence').first()).toContainText('Campaign finance');
  await expect(page.getByTestId('finance-evidence').first()).toContainText('$1,250,000');
  await expect(page.getByTestId('finance-evidence').first()).toContainText('Financial context, not a forecast.');
  await expect(page.getByTestId('historical-evidence').first()).toContainText('R+2.5');
  await expect(page.getByTestId('turnout-evidence').first()).toContainText('61.0%');
  await expect(page.getByTestId('cvap-evidence').first()).toContainText('538,816');
  await expect(page.getByTestId('congress-evidence').first()).toContainText('Official Example Act');
  await expect(page.getByTestId('unavailable-evidence')).toContainText('FEC totals are unavailable.');
  await expect(page.getByTestId('unavailable-evidence')).toContainText('Official source could not be validated.');
  await expect(page.getByTestId('picks-unavailable-2026-CA-senate-class-1')).toContainText('official candidate allowlist');
  await expect(page.getByTestId('pick-fec-canonical')).toContainText('Picks unavailable');
  await expect(page.getByTestId('pick-fec-canonical')).toBeDisabled();
  await expect(page.getByTestId('race-2026-GA-senate-class-2')).toBeVisible();
  await expect(page.getByTestId('picks-unavailable-2026-GA-senate-class-2')).toBeVisible();
  await expect(page.getByTestId('race-2026-GA-senate-class-2').getByRole('button')).toBeDisabled();
  await expect(page.getByTestId('race-2026-VA-house-001')).toBeVisible();
  await expect(page.getByTestId('race-2026-VA-house-001').getByRole('button')).toContainText('Make pick');
  await page.getByTestId('race-2026-VA-house-001').getByRole('button').click();
  await expect(page.getByTestId('race-2026-VA-house-001').getByRole('button')).toContainText('Pick recorded');
  await expect(page.getByTestId('race-browser-closed-2026')).toContainText('Picking closed');
  await expect(page.getByTestId('race-browser-closed-2026').getByRole('button')).toBeDisabled();
  await expect(page.getByTestId('race-fixture-race-2024-sandbox')).toHaveCount(0);
});

test('local create, invite join, combined filters, measure create, and measure update work on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/?browser-test=league-workflow');
  await page.getByLabel('League name').fill('G7.2 League');
  await page.getByRole('button', { name: 'Create league' }).click();
  await expect(page.getByRole('status')).toContainText('G72CA');
  await page.getByLabel('Invite code').fill('G72CA');
  await page.getByRole('button', { name: 'Join league' }).click();
  await expect(page.getByText(/league joined/i)).toBeVisible();
  await page.getByLabel('State').selectOption('CA');
  await page.getByLabel('Office or contest type').selectOption('Measure');
  await page.getByLabel('Race or measure').selectOption('measure');
  await page.getByLabel('Prediction readiness').selectOption('ready');
  await expect(page.getByTestId('catalog-result-count')).toHaveText('14 results');
  const proposition = page.getByTestId('workflow-measure-2026-CA-proposition-1');
  await proposition.getByRole('button', { name: 'Pick yes' }).click();
  await expect(proposition).toContainText('Saved pick: yes');
  await proposition.getByRole('button', { name: 'Pick no' }).click();
  await expect(proposition).toContainText('Saved pick: no');
  await page.getByLabel('State').selectOption({ label: 'All states' });
  await page.getByLabel('Office or contest type').selectOption('Senate');
  await page.getByLabel('Race or measure').selectOption('measure');
  await expect(page.getByText(/no contests match/i)).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters' }).last().click();
  await expect(page.getByTestId('catalog-result-count')).toHaveText('15 results');
  await expect(page.getByTestId('workflow-race-2026-CA-senate-class-1')).toContainText('official candidate allowlist');
});
