import { ExternalLink } from 'lucide-react';
import { formatEvidenceCurrency, formatEvidenceNumber, parseCanonicalEvidence, partisanMarginLabel, type EvidenceAvailability, type EvidenceSource } from '../lib/canonicalEvidence';

const stateLabel: Record<EvidenceAvailability, string> = { present: 'Available', partial: 'Partial', unavailable: 'Unavailable', not_applicable: 'Not applicable', stale: 'Stale', source_error: 'Source error' };
function Status({ value }: { value: EvidenceAvailability }) { return <span className="text-[9px] font-mono uppercase border border-slate-700 px-2 py-1 text-slate-400">{stateLabel[value]}</span>; }
function Provenance({ evidence }: { evidence: EvidenceSource }) { return <div className="mt-3 space-y-1 text-[9px] font-mono text-slate-500"><p>{evidence.sourceVintage ? `Vintage: ${evidence.sourceVintage}` : ''}{evidence.retrievedAt ? ` · Retrieved ${new Date(evidence.retrievedAt).toLocaleDateString()}` : ''}</p>{evidence.methodology && <p>{evidence.methodology}</p>}{evidence.sourceUrl && <a className="inline-flex items-center gap-1 text-slate-400 hover:text-white" href={evidence.sourceUrl} target="_blank" rel="noopener noreferrer">Official source <ExternalLink size={10} /></a>}</div>; }
function Missing({ reason, methodology }: { reason?: string; methodology?: string }) { return <p className="text-xs text-slate-500">{reason ?? methodology ?? 'This evidence is not available from the certified source.'}</p>; }

export function CanonicalEvidencePanels({ research, metrics, loading = false, error = null }: { research: unknown; metrics: unknown; loading?: boolean; error?: string | null }) {
  if (loading) return <p className="text-sm text-slate-500" data-testid="evidence-loading">Loading sourced evidence…</p>;
  if (error) return <p role="alert" className="text-sm text-brand-red">{error}</p>;
  if (!research && !metrics) return <p className="text-sm text-slate-500">No canonical evidence is available yet.</p>;
  const evidence = parseCanonicalEvidence(research, metrics); const finance = evidence.finance; const congress = evidence.congress;
  const identityValue = evidence.identity.value && typeof evidence.identity.value === 'object' && 'fecCandidateId' in evidence.identity.value ? String((evidence.identity.value as { fecCandidateId: unknown }).fecCandidateId) : undefined;
  return <div className="grid grid-cols-1 xl:grid-cols-3 gap-6" data-testid="canonical-evidence">
    <div className="xl:col-span-2 space-y-6">
      {evidence.issues.length > 0 && <div role="alert" className="border border-amber-600 p-3 text-xs text-amber-300">Some malformed evidence was withheld safely: {evidence.issues.join(' ')}</div>}
      <section className="bg-black/40 p-6 brutalist-card" data-testid="identity-evidence"><div className="flex justify-between gap-3"><h2 className="text-lg font-black uppercase italic">Official identity</h2><Status value={evidence.identity.availability} /></div>{identityValue ? <p className="mt-3 text-sm text-slate-300">FEC candidate ID: <span className="font-mono">{identityValue}</span></p> : <Missing reason={evidence.identity.reason} methodology={evidence.identity.methodology} />}<Provenance evidence={evidence.identity} /></section>
      <section className="bg-black/40 p-6 brutalist-card" data-testid="finance-evidence"><div className="flex justify-between gap-3"><div><h2 className="text-lg font-black uppercase italic">Campaign finance</h2><p className="text-[10px] text-slate-500">Financial context, not a forecast.</p></div><Status value={finance.availability} /></div>{finance.availability === 'present' ? <><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{[['Receipts',finance.totalReceipts],['Disbursements',finance.totalDisbursements],['Cash on hand',finance.cashOnHand],['Debt',finance.debtsOwed]].map(([label,value]) => <div className="border border-slate-800 p-3" key={String(label)}><p className="text-[9px] uppercase text-slate-500">{label}</p><p className="text-sm font-black mt-1">{formatEvidenceCurrency(value as number | undefined)}</p></div>)}</div><p className="text-[10px] text-slate-500 mt-3">Cycle {finance.cycle ?? 'Unavailable'} · Through {finance.filingPeriod ?? 'an unavailable period'}</p></> : <Missing reason={finance.reason} methodology={finance.methodology} />}<Provenance evidence={finance} /></section>
      <section className="bg-black/40 p-6 brutalist-card" data-testid="congress-evidence"><div className="flex justify-between gap-3"><h2 className="text-lg font-black uppercase italic">Congressional record</h2><Status value={congress.availability} /></div>{congress.availability === 'present' ? <div className="mt-4 space-y-5"><p className="text-sm text-slate-300">{congress.officialName} · {congress.chamber} · {congress.state} · Bioguide {congress.bioguideId}</p><div className="grid grid-cols-2 gap-3"><div className="border border-slate-800 p-3"><p className="text-[9px] uppercase text-slate-500">Sponsored bills</p><p className="text-2xl font-black">{congress.sponsored.length}</p></div><div className="border border-slate-800 p-3"><p className="text-[9px] uppercase text-slate-500">Cosponsored bills</p><p className="text-2xl font-black">{congress.cosponsored.length}</p></div></div>{congress.sponsored.slice(0,3).map((bill) => <a key={bill.identifier} href={bill.sourceUrl} target="_blank" rel="noopener noreferrer" className="block border-l-2 border-brand-red pl-3 text-xs text-slate-300 hover:text-white"><strong>{bill.identifier}</strong> — {bill.title}</a>)}<div><h3 className="text-xs font-black uppercase mb-2">Reviewed roll calls ({congress.votes.length})</h3>{congress.votes.slice(0,5).map((vote) => <a key={`${vote.chamber}-${vote.rollNumber}`} href={vote.sourceUrl} target="_blank" rel="noopener noreferrer" className="flex justify-between gap-3 border-t border-slate-800 py-2 text-xs"><span>{vote.title}</span><span className="font-mono">{vote.vote}</span></a>)}</div></div> : <div className="mt-3"><Missing reason={congress.reason} methodology={congress.methodology} /></div>}<Provenance evidence={congress} /></section>
    </div>
    <aside className="space-y-6">
      <section className="bg-black/40 p-6 brutalist-card" data-testid="historical-evidence"><div className="flex justify-between gap-3"><h2 className="text-sm font-black uppercase italic">Historical margin</h2><Status value={evidence.historical.availability} /></div>{evidence.historical.availability === 'present' && evidence.historical.marginPct !== undefined ? <><p className="text-3xl font-black mt-4">{partisanMarginLabel(evidence.historical.marginPct)}</p><div className="h-3 bg-slate-800 mt-3" aria-label={`Historical partisan margin ${partisanMarginLabel(evidence.historical.marginPct)}`}><div className={evidence.historical.marginPct >= 0 ? 'h-full bg-blue-600' : 'h-full bg-brand-red'} style={{ width: `${Math.min(100, Math.abs(evidence.historical.marginPct) * 5)}%` }} /></div><p className="text-[10px] text-slate-500 mt-2">{evidence.historical.electionYear} · {formatEvidenceNumber(evidence.historical.totalVotes)} total votes</p></> : <div className="mt-3"><Missing reason={evidence.historical.reason} methodology={evidence.historical.methodology} /></div>}<Provenance evidence={evidence.historical} /></section>
      <section className="bg-black/40 p-6 brutalist-card" data-testid="turnout-evidence"><div className="flex justify-between gap-3"><h2 className="text-sm font-black uppercase italic">Turnout context</h2><Status value={evidence.turnout.availability} /></div>{evidence.turnout.availability === 'present' && evidence.turnout.turnoutProxy !== undefined ? <><p className="text-3xl font-black mt-4">{(evidence.turnout.turnoutProxy * 100).toFixed(1)}%</p><p className="text-[10px] text-slate-500">Votes divided by ACS CVAP; not official turnout.</p></> : <div className="mt-3"><Missing reason={evidence.turnout.reason} methodology={evidence.turnout.methodology} /></div>}<Provenance evidence={evidence.turnout} /></section>
      <section className="bg-black/40 p-6 brutalist-card" data-testid="cvap-evidence"><div className="flex justify-between gap-3"><h2 className="text-sm font-black uppercase italic">Citizen voting-age population</h2><Status value={evidence.cvap.availability} /></div>{evidence.cvap.availability === 'present' ? <><p className="text-3xl font-black mt-4">{formatEvidenceNumber(evidence.cvap.cvapEstimate)}</p><p className="text-[10px] text-slate-500">{evidence.cvap.geography} · {evidence.cvap.estimateVintage} ACS vintage</p></> : <div className="mt-3"><Missing reason={evidence.cvap.reason} methodology={evidence.cvap.methodology} /></div>}<Provenance evidence={evidence.cvap} /></section>
    </aside>
  </div>;
}
