import { createHash } from 'node:crypto';
import { buildCanonicalPublicationPlan, validateCanonicalPublicationSnapshot } from './canonicalPublication.js';
import { buildFecFinanceBaselinePlan } from './fecFinanceDepth.js';
import { validateFecBulkFinanceSnapshot } from './fecBulkFinance.js';

type Json = Record<string, unknown>;
export type CongressChamber = 'House' | 'Senate';
export type VoteMember = { bioguideId?: string; firstName?: string; lastName?: string; state?: string; voteCast?: string };
export type CongressCandidateReference = { raceId: string; candidateId: string; state: string; chamber: CongressChamber };
export type CongressProfile = { chamber: CongressChamber; state: string; district: string | null; partyHistory: Array<{ party: string; startYear: number | null }>; terms: Array<{ chamber: CongressChamber; state: string; district: string | null; startYear: number | null; endYear: number | null }>; officialName: string; sourceUrl: string; retrievedAt: string };
export type CongressLegislation = { identifier: string; title: string; introducedDate: string | null; latestAction: { text: string | null; date: string | null }; sourceUrl: string };
export type CongressVote = { chamber: CongressChamber; congress: 119; session: 2; rollNumber: number; date: string; question: string | null; title: string | null; result: string | null; vote: 'Yea' | 'Nay' | 'Present' | null; sourceUrl: string; matchingMethod: 'bioguide-exact' | 'senate-name-state-exact' | 'unavailable' };
export type CongressCandidateCapture = { bioguideId: string; references: CongressCandidateReference[]; status: 'present' | 'unavailable'; failureReason?: string; profile?: CongressProfile; sponsored: CongressLegislation[]; cosponsored: CongressLegislation[]; votes: CongressVote[] };
export type CongressDepthSnapshot = { schemaVersion: 1; capturedAt: string; publicationInputDigest: string; financeInputDigest: string; calls: number; maxCalls: number; candidates: CongressCandidateCapture[]; rollCalls: Array<{ chamber: CongressChamber; congress: 119; session: 2; rollNumber: number; sourceUrl: string }>; inputDigest: string };
const isRecord = (value: unknown): value is Json => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const text = (value: unknown) => typeof value === 'string' ? value.trim() : '';
const stable = (value: unknown): string => Array.isArray(value) ? `[${value.map(stable).join(',')}]` : isRecord(value) ? `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}` : JSON.stringify(value);
const digest = (value: unknown) => createHash('sha256').update(stable(value)).digest('hex');
const ordered = <T>(values: T[], key: (value: T) => string) => [...values].sort((left, right) => key(left).localeCompare(key(right)));
const date = (value: unknown) => Boolean(text(value)) && Number.isFinite(Date.parse(text(value)));
export function normalizeCongressMemberName(value: string): string { const words = value.toUpperCase().replace(/[^A-Z, ]/g, ' ').split(/[ ,]+/).filter(Boolean); if (value.includes(',') && words.length >= 2) return [...words.slice(1), words[0]!].join(' '); return words.join(' '); }
export function matchHouseVote(member: VoteMember, bioguideId: string): boolean { return Boolean(member.bioguideId) && member.bioguideId!.trim().toUpperCase() === bioguideId.trim().toUpperCase(); }
export function matchSenateVote(members: VoteMember[], identity: { officialName: string; state: string }): { status: 'matched'; member: VoteMember } | { status: 'unavailable' | 'ambiguous' } { const expected = normalizeCongressMemberName(identity.officialName); const matches = members.filter((member) => text(member.state).toUpperCase() === identity.state.toUpperCase() && normalizeCongressMemberName(`${text(member.firstName)} ${text(member.lastName)}`) === expected); return matches.length === 1 ? { status: 'matched', member: matches[0]! } : { status: matches.length ? 'ambiguous' : 'unavailable' }; }
function validCandidate(value: unknown): value is CongressCandidateCapture { if (!isRecord(value) || !/^[A-Z]\d{6}$/.test(text(value.bioguideId)) || !Array.isArray(value.references) || !['present', 'unavailable'].includes(text(value.status)) || !Array.isArray(value.sponsored) || !Array.isArray(value.cosponsored) || !Array.isArray(value.votes)) return false; return value.references.every((reference) => isRecord(reference) && text(reference.raceId) && text(reference.candidateId) && /^[A-Z]{2}$/.test(text(reference.state)) && ['House', 'Senate'].includes(text(reference.chamber))); }
export function buildCongressDepthSnapshot(value: Omit<CongressDepthSnapshot, 'schemaVersion' | 'capturedAt' | 'publicationInputDigest' | 'financeInputDigest' | 'inputDigest'> & { source: { publicationInputDigest: string; financeInputDigest: string; capturedAt: string } }): CongressDepthSnapshot { if (!/^[a-f0-9]{64}$/.test(value.source.publicationInputDigest) || !/^[a-f0-9]{64}$/.test(value.source.financeInputDigest) || !date(value.source.capturedAt) || !Number.isInteger(value.calls) || !Number.isInteger(value.maxCalls) || value.calls < 0 || value.calls > value.maxCalls || value.maxCalls > 1600 || !value.candidates.every(validCandidate)) throw new Error('invalid Congress depth capture'); const candidates = ordered(value.candidates, (item) => item.bioguideId).map((candidate) => ({ ...candidate, references: ordered(candidate.references, (reference) => `${reference.raceId}/${reference.candidateId}`), sponsored: ordered(candidate.sponsored, (bill) => bill.identifier), cosponsored: ordered(candidate.cosponsored, (bill) => bill.identifier), votes: ordered(candidate.votes, (vote) => `${vote.chamber}/${vote.rollNumber}`) })); const rollCalls = ordered(value.rollCalls, (vote) => `${vote.chamber}/${vote.rollNumber}`); const payload = { capturedAt: value.source.capturedAt, publicationInputDigest: value.source.publicationInputDigest, financeInputDigest: value.source.financeInputDigest, calls: value.calls, maxCalls: value.maxCalls, candidates, rollCalls }; return { schemaVersion: 1, ...payload, inputDigest: digest(payload) }; }
export function validateCongressDepthSnapshot(value: unknown): CongressDepthSnapshot { if (!isRecord(value) || value.schemaVersion !== 1 || !date(value.capturedAt) || !Array.isArray(value.candidates) || !Array.isArray(value.rollCalls)) throw new Error('invalid Congress depth snapshot'); const snapshot = buildCongressDepthSnapshot({ source: { publicationInputDigest: text(value.publicationInputDigest), financeInputDigest: text(value.financeInputDigest), capturedAt: text(value.capturedAt) }, calls: value.calls as number, maxCalls: value.maxCalls as number, candidates: value.candidates as CongressCandidateCapture[], rollCalls: value.rollCalls as CongressDepthSnapshot['rollCalls'] }); if (snapshot.inputDigest !== value.inputDigest) throw new Error('Congress depth snapshot digest mismatch'); return snapshot; }

export function canonicalCongressReferences(snapshotValue: unknown): Map<string, CongressCandidateReference[]> {
  const snapshot = validateCanonicalPublicationSnapshot(snapshotValue); const plan = buildCanonicalPublicationPlan(snapshot.inputs); const grouped = new Map<string, CongressCandidateReference[]>();
  for (const document of plan.documents.filter((item) => /^races\/[^/]+$/.test(item.path))) {
    const race = document.data as { id: string; state: string; office: CongressChamber; candidates: Array<{ id: string; externalIds?: { bioguideId?: string } }> };
    for (const candidate of race.candidates) { const id = text(candidate.externalIds?.bioguideId).toUpperCase(); if (!/^[A-Z]\d{6}$/.test(id)) continue; const refs = grouped.get(id) ?? []; refs.push({ raceId: race.id, candidateId: candidate.id, state: race.state, chamber: race.office }); grouped.set(id, refs); }
  }
  return new Map(ordered([...grouped.entries()], ([id]) => id).map(([id, refs]) => [id, ordered(refs, (reference) => `${reference.raceId}/${reference.candidateId}`)]));
}

export function buildCongressResearchPlan(publicationValue: unknown, financeValue: unknown, congressValue: unknown) {
  const publication = validateCanonicalPublicationSnapshot(publicationValue); const finance = validateFecBulkFinanceSnapshot(financeValue); const congress = validateCongressDepthSnapshot(congressValue);
  if (finance.capture.sourceSnapshotInputDigest !== publication.inputDigest || congress.publicationInputDigest !== publication.inputDigest || congress.financeInputDigest !== finance.inputDigest) throw new Error('Congress depth source digest mismatch');
  const baseline = buildFecFinanceBaselinePlan(publication, finance.capture); const references = canonicalCongressReferences(publication); const byCandidate = new Map<string, CongressCandidateCapture>();
  for (const captured of congress.candidates) for (const reference of captured.references) { const key = `${reference.raceId}/${reference.candidateId}`; if (byCandidate.has(key)) throw new Error(`duplicate Congress candidate reference: ${key}`); byCandidate.set(key, captured); }
  const documents = baseline.documents.map((document) => { const match = /^races\/([^/]+)\/candidateResearch\/([^/]+)$/.exec(document.path); if (!match) return document; const key = `${match[1]}/${match[2]}`; const captured = byCandidate.get(key); const hasBioguide = [...references.values()].flat().some((reference) => `${reference.raceId}/${reference.candidateId}` === key); const congressional = !hasBioguide ? { availability: 'not_applicable', methodology: 'No reviewed Bioguide identity is attached to this canonical candidate; no congressional record was inferred.' } : !captured || captured.status === 'unavailable' ? { availability: 'unavailable', methodology: captured?.failureReason ?? 'Official congressional response was unavailable.', sourceUrl: captured?.profile?.sourceUrl ?? null } : { availability: 'present', bioguideId: captured.bioguideId, profile: captured.profile, sponsored: captured.sponsored, cosponsored: captured.cosponsored, votes: captured.votes, methodology: 'Official Congress.gov and Senate.gov records; no ideology, eligibility, attendance, or forecast inference.' }; return { ...document, data: { ...document.data, congressDepth: congressional } }; });
  const counts = { research: documents.filter((document) => /candidateResearch/.test(document.path)).length, measures: documents.filter((document) => document.path.startsWith('ballotMeasures/')).length, metrics: documents.filter((document) => document.path.startsWith('contestMetrics/')).length }; if (counts.research !== 2384 || counts.measures !== 14 || counts.metrics !== 470) throw new Error('G6.1 cardinality regression');
  const coverage = { bioguideReferences: [...references.values()].reduce((sum, values) => sum + values.length, 0), uniqueBioguideIds: references.size, profilesPresent: congress.candidates.filter((candidate) => candidate.status === 'present' && candidate.profile).length, unavailableProfiles: congress.candidates.filter((candidate) => candidate.status === 'unavailable').length, houseVotes: congress.rollCalls.filter((vote) => vote.chamber === 'House').length, senateVotes: congress.rollCalls.filter((vote) => vote.chamber === 'Senate').length, counts };
  const evidenceDigest = digest({ baseline: baseline.evidenceDigest, congress: congress.inputDigest, documents }); return { ...baseline, documents, inputDigest: digest({ baseline: baseline.inputDigest, congress: congress.inputDigest }), evidenceDigest, planDigest: digest({ documents, coverage, evidenceDigest }), congressCoverage: coverage };
}
