import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { CANONICAL_2026_FEDERAL_CONTESTS } from '../../ingest/src/federalRegistry.js';
import { buildCanonicalMeasurePlan } from './canonicalBallotMeasures.js';
import { buildCanonicalPublicationPlan, validateCanonicalPublicationSnapshot, type CanonicalPublicationSnapshot, type PublicationDocument } from './canonicalPublication.js';

type Json = Record<string, unknown>;
type Availability = 'present' | 'unavailable' | 'not_applicable';
export type BaselineDocument = { path: string; data: Json };
export type ResearchMetricsBaselinePlan = {
  schemaVersion: 1;
  documents: BaselineDocument[];
  inputDigest: string;
  evidenceDigest: string;
  planDigest: string;
  coverage: {
    rawRaces: number; canonicalRaces: number;
    candidateResearch: { documents: number; richPreserved: number; baselineOnly: number };
    measureResearch: { documents: number };
    metrics: { documents: number; preserved: number; coverageOnly: number; coverageOnlyRaceIds: string[]; depth: Record<'historical' | 'turnout' | 'demographicsCvap' | 'comparativeFinance', Record<Availability, number>> };
  };
  audit: { duplicateDocuments: number; orphanDocuments: number; leakage: number; metricsReady: number };
};

const isRecord = (value: unknown): value is Json => value !== null && typeof value === 'object' && !Array.isArray(value);
const stable = (value: unknown): string => Array.isArray(value) ? `[${value.map(stable).join(',')}]` : isRecord(value) ? `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}` : JSON.stringify(value);
const digest = (value: unknown) => createHash('sha256').update(stable(value)).digest('hex');
const order = <T>(items: T[], key: (item: T) => string) => [...items].sort((a, b) => key(a).localeCompare(key(b)));
const text = (value: unknown) => typeof value === 'string' ? value.trim() : '';
const availability = (state: Availability, source: Json) => ({ availability: state, ...source });

/**
 * Removes only capture-derived metadata from certification projections. The
 * full product documents retain these fields for provenance; certification
 * digests must not change when an otherwise identical publication is captured
 * at a different time. Derived nested evidence digests are omitted because
 * their source values remain in the same projection.
 */
export function projectCertificationValue(value: unknown, publicationCapturedAt: string): unknown {
  if (Array.isArray(value)) return value.map((item) => projectCertificationValue(item, publicationCapturedAt));
  if (!isRecord(value)) return value;
  const projected: Json = {};
  for (const [key, child] of Object.entries(value)) {
    if (key === 'evidenceDigest') continue;
    if ((key === 'capturedAt' || key === 'asOf' || key === 'retrievedAt') && child === publicationCapturedAt) continue;
    projected[key] = projectCertificationValue(child, publicationCapturedAt);
  }
  return projected;
}
const officialFec = (candidateId: string, capturedAt: string) => {
  const fecCandidateId = candidateId.replace(/^fec-/, '');
  if (!/^[HS]\d[A-Z]{2}\d{5}$/.test(fecCandidateId)) throw new Error(`canonical candidate lacks an FEC identity: ${candidateId}`);
  const sourceUrl = `https://www.fec.gov/data/candidate/${fecCandidateId}/`;
  const source = { sourceId: `fec-${fecCandidateId}`, sourceUrl, verificationLevel: 'official', asOf: capturedAt, retrievedAt: capturedAt, sourceVintage: 'canonical-publication-schema-v3' };
  return {
    identity: availability('present', { value: { fecCandidateId }, ...source, methodology: 'Canonical identity mapping points to the official FEC candidate record.' }),
    filing: availability('present', { value: { fecCandidateId }, ...source, methodology: 'FEC candidate-record identity is retained; filing does not assert active candidacy, ballot status, or pick eligibility.' }),
    finance: availability('unavailable', { ...source, methodology: 'No finance value was supplied by the certified offline snapshot.' }),
    congress: availability('unavailable', { ...source, methodology: 'No Congress.gov record was inferred from the FEC identity.' }),
    rollCall: availability('not_applicable', { ...source, methodology: 'Roll-call coverage requires a sourced congressional member mapping.' }),
    biography: availability('unavailable', { ...source, methodology: 'No biography is generated by this baseline.' }),
  };
};
function assertNoLeakage(value: unknown, location: string): void {
  if (Array.isArray(value)) { value.forEach((item, index) => assertNoLeakage(item, `${location}[${index}]`)); return; }
  if (!isRecord(value)) return;
  for (const [key, child] of Object.entries(value)) {
    if (/(winner|post.?lock|future.?result|certified.?result)/i.test(key)) throw new Error(`historical leakage field rejected: ${location}.${key}`);
    assertNoLeakage(child, `${location}.${key}`);
  }
}
function metricField(data: Json, name: 'historical' | 'turnout' | 'demographicsCvap' | 'comparativeFinance'): Availability {
  if (name === 'demographicsCvap') return isRecord(data.demographics) ? 'present' : 'unavailable';
  if (name === 'comparativeFinance') return isRecord(data.comparativeFinance) ? 'present' : 'unavailable';
  return isRecord(data[name]) ? 'present' : 'unavailable';
}
function coverageMetric(race: { id: string; state: string; district: string | null; office: string }, capturedAt: string): Json {
  const source = { sourceId: `canonical-registry-${race.id}`, sourceUrl: 'https://www.fec.gov/data/', verificationLevel: 'official', asOf: capturedAt, retrievedAt: capturedAt, sourceVintage: 'canonical-2026-federal-registry' };
  const unavailable = (methodology: string) => availability('unavailable', { ...source, methodology });
  return { id: race.id, raceId: race.id, baselineMetrics: {
    geography: { state: race.state, district: race.district, office: race.office, methodology: 'Canonical federal registry geography; no inferred district aggregation.' },
    electionVintage: { targetElectionYear: 2026, methodology: 'Baseline does not use future election results.' },
    historical: unavailable('No sourced historical margin is available in the certified snapshot.'),
    turnout: unavailable('No sourced turnout value is available in the certified snapshot.'),
    demographicsCvap: unavailable('No sourced Census, ACS, or CVAP value is available in the certified snapshot.'),
    comparativeFinance: unavailable('No sourced comparative finance value is available in the certified snapshot.'),
  }, baselineResearchContract: { schemaVersion: 1, evidenceDigest: digest({ race: race.id, capturedAt, kind: 'coverage-only-metric' }) } };
}

/** Validates the source only; it performs no Firebase import or credential lookup. */
export function validateResearchMetricsBaselineSnapshot(value: unknown): CanonicalPublicationSnapshot {
  return validateCanonicalPublicationSnapshot(value);
}

/** Reconstructs the 470-seat certified publication plan and adds only explicit offline baseline fields. */
export function buildResearchMetricsBaseline(snapshotValue: unknown): ResearchMetricsBaselinePlan {
  const snapshot = validateResearchMetricsBaselineSnapshot(snapshotValue);
  const publication = buildCanonicalPublicationPlan(snapshot.inputs);
  if (publication.expectedCounts.races !== CANONICAL_2026_FEDERAL_CONTESTS.length || CANONICAL_2026_FEDERAL_CONTESTS.length !== 470) throw new Error('canonical federal registry must contain exactly 470 races');
  if (publication.mapping.publicationCandidateConflicts.length || publication.mapping.publicationResearchConflicts.length || publication.mapping.publicationMetricConflicts.length) throw new Error('canonical publication has unresolved mapping conflicts');
  const raceDocuments = publication.documents.filter((document) => /^races\/[^/]+$/.test(document.path));
  const richDocuments = publication.documents.filter((document) => /^races\/[^/]+\/candidateResearch\/[^/]+$/.test(document.path));
  const metrics = publication.documents.filter((document) => /^contestMetrics\/[^/]+$/.test(document.path));
  const richByKey = new Map(richDocuments.map((document) => [document.path.replace(/^races\/([^/]+)\/candidateResearch\//, '$1/'), document]));
  const candidates = raceDocuments.flatMap((race) => {
    const raceId = text(race.data.id);
    const values = Array.isArray(race.data.candidates) ? race.data.candidates : [];
    return values.map((candidate) => ({ raceId, candidate: candidate as Json }));
  });
  const researchDocuments = order(candidates.map(({ raceId, candidate }) => {
    const candidateId = text(candidate.id); const key = `${raceId}/${candidateId}`; const rich = richByKey.get(key);
    const baseline = officialFec(candidateId, snapshot.capturedAt);
    return { path: `races/${raceId}/candidateResearch/${candidateId}`, data: {
      ...(rich?.data ?? {}), raceId, candidateId, baselineResearch: { schemaVersion: 1, evidenceDigest: digest({ raceId, candidateId, baseline }), fields: baseline },
    } };
  }), (document) => document.path);
  const measureRegistry = JSON.parse(readFileSync('data/2026/statewide-ballot-measures.json', 'utf8'));
  const measurePlan = buildCanonicalMeasurePlan(measureRegistry);
  const measureResearch = order(measurePlan.documents.map((document) => {
    const data = document.data; const id = text(data.id); const source = { sourceId: `measure-${id}`, sourceUrl: text(data.sourceUrl), verificationLevel: 'official', asOf: text(data.reviewedAt), retrievedAt: text(data.retrievedAt), sourceVintage: text(data.electionDate) };
    const fields = {
      title: availability('present', { value: data.title, ...source, methodology: 'Official statewide measure registry.' }),
      description: availability('present', { value: data.description, ...source, methodology: 'Official statewide measure registry.' }),
      qualification: availability('present', { value: data.qualificationStatus, ...source, methodology: 'Official statewide measure registry.' }),
      sourceHistory: availability('present', { value: [{ sourceId: source.sourceId, sourceUrl: source.sourceUrl, retrievedAt: source.retrievedAt, reviewedAt: source.asOf }], ...source, methodology: 'Tracked official-source history from the certified measure plan.' }),
      fullText: text(data.fullTextUrl) ? availability('present', { value: data.fullTextUrl, ...source, methodology: 'Official linked text.' }) : availability('unavailable', { ...source, methodology: 'No official full-text URL was supplied.' }),
      fiscalAnalysis: text(data.fiscalAnalysisUrl) ? availability('present', { value: data.fiscalAnalysisUrl, ...source, methodology: 'Official linked fiscal analysis.' }) : availability('unavailable', { ...source, methodology: 'No official fiscal-analysis URL was supplied.' }),
    };
    return { path: `ballotMeasures/${id}/research/baseline`, data: { measureId: id, baselineResearch: { schemaVersion: 1, evidenceDigest: digest({ id, fields }), fields } } };
  }), (document) => document.path);
  const metricByRace = new Map(metrics.map((document) => [text(document.data.raceId), document]));
  const metricDocuments = order(CANONICAL_2026_FEDERAL_CONTESTS.map((race) => {
    const existing = metricByRace.get(race.id);
    if (existing) {
      assertNoLeakage(existing.data, existing.path);
      const fields = Object.fromEntries((['historical', 'turnout', 'demographicsCvap', 'comparativeFinance'] as const).map((name) => [name, metricField(existing.data, name)]));
      return { path: `contestMetrics/${race.id}`, data: { ...existing.data, baselineMetrics: { geography: { state: race.state, district: race.district, office: race.office, methodology: 'Canonical federal registry geography.' }, electionVintage: { targetElectionYear: 2026, methodology: 'Baseline preserves source vintages and rejects future/post-lock results.' }, fieldAvailability: fields, evidenceDigest: digest({ raceId: race.id, fields, source: existing.data }) } } };
    }
    return { path: `contestMetrics/${race.id}`, data: coverageMetric(race, snapshot.capturedAt) };
  }), (document) => document.path);
  const documents = order([...researchDocuments, ...measureResearch, ...metricDocuments], (document) => document.path);
  const paths = new Set<string>(); let duplicateDocuments = 0; let orphanDocuments = 0;
  for (const document of documents) { if (paths.has(document.path)) duplicateDocuments += 1; paths.add(document.path); }
  const candidateKeys = new Set(candidates.map(({ raceId, candidate }) => `${raceId}/${text(candidate.id)}`));
  for (const document of researchDocuments) if (!candidateKeys.has(document.path.replace(/^races\/([^/]+)\/candidateResearch\//, '$1/'))) orphanDocuments += 1;
  for (const document of metricDocuments) if (!CANONICAL_2026_FEDERAL_CONTESTS.some((race) => race.id === text(document.data.raceId))) orphanDocuments += 1;
  const depth = { historical: { present: 0, unavailable: 0, not_applicable: 0 }, turnout: { present: 0, unavailable: 0, not_applicable: 0 }, demographicsCvap: { present: 0, unavailable: 0, not_applicable: 0 }, comparativeFinance: { present: 0, unavailable: 0, not_applicable: 0 } };
  for (const metric of metricDocuments) for (const name of Object.keys(depth) as Array<keyof typeof depth>) {
    const state = isRecord(metric.data.baselineMetrics) && isRecord(metric.data.baselineMetrics.fieldAvailability) ? metric.data.baselineMetrics.fieldAvailability[name] : isRecord(metric.data.baselineMetrics) && isRecord(metric.data.baselineMetrics[name]) ? text(metric.data.baselineMetrics[name].availability) : 'unavailable';
    depth[name][state === 'present' || state === 'not_applicable' ? state : 'unavailable'] += 1;
  }
  const coverageOnlyRaceIds = CANONICAL_2026_FEDERAL_CONTESTS.filter((race) => !metricByRace.has(race.id)).map((race) => race.id);
  const certificationDocuments = projectCertificationValue(documents, snapshot.capturedAt);
  const evidenceDigest = digest({ snapshotInput: snapshot.inputDigest, publicationPlan: publication.planDigest, measurePlan: measurePlan.planDigest, documents: certificationDocuments });
  const coverage = { rawRaces: snapshot.inputs.races.length, canonicalRaces: raceDocuments.length, candidateResearch: { documents: researchDocuments.length, richPreserved: richDocuments.length, baselineOnly: researchDocuments.length - richDocuments.length }, measureResearch: { documents: measureResearch.length }, metrics: { documents: metricDocuments.length, preserved: metrics.length, coverageOnly: coverageOnlyRaceIds.length, coverageOnlyRaceIds, depth } };
  const audit = { duplicateDocuments, orphanDocuments, leakage: 0, metricsReady: metricDocuments.filter((document) => Object.values(isRecord(document.data.baselineMetrics) && isRecord(document.data.baselineMetrics.fieldAvailability) ? document.data.baselineMetrics.fieldAvailability : {}).some((value) => value === 'present')).length };
  const inputDigest = digest({ snapshot: snapshot.inputDigest, canonicalRegistry: CANONICAL_2026_FEDERAL_CONTESTS, measureRegistry });
  return { schemaVersion: 1, documents, inputDigest, evidenceDigest, planDigest: digest({ documents: certificationDocuments, coverage, audit, evidenceDigest }), coverage, audit };
}
