import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import process from 'node:process';
import { WAVE_C_STATES, buildWaveCReport, fetchWaveCPdfProvider, normalizeWaveCPdfFixture, type WaveCState } from './lib/waveCPdfProviders.js';

const privateRoot = resolve(process.cwd(), '.artifacts', 'private', 'canonical-migration');
const fixtureRoot = resolve(process.cwd(), 'data', '2026', 'wave-c-pdf');
type Options = { states: WaveCState[]; fetch: boolean; fixtureDir: string; snapshotIn?: string; snapshotOut?: string; reportOut?: string; replay: boolean };
function privatePath(value: string, flag: string) { const path = resolve(process.cwd(), value); const child = relative(privateRoot, path); if (!child || child.startsWith('..') || !path.endsWith('.json')) throw new Error(`${flag} must be a JSON file beneath .artifacts/private/canonical-migration`); return path; }
function parseArgs(args: string[]): Options { const result: Options = { states: [...WAVE_C_STATES], fetch: false, fixtureDir: fixtureRoot, replay: false }; for (let index = 0; index < args.length; index += 1) { const flag = args[index]; if (flag === '--all-wave-c' || flag === '--dry-run') continue; if (flag === '--fetch') { result.fetch = true; continue; } if (flag === '--verify-replay') { result.replay = true; continue; } const value = args[++index]; if (!value) throw new Error(`missing value for ${flag}`); if (flag === '--state') { const state = value.toUpperCase() as WaveCState; if (!WAVE_C_STATES.includes(state)) throw new Error(`unknown Wave C state: ${value}`); result.states = [state]; continue; } if (flag === '--fixture-dir') { result.fixtureDir = resolve(process.cwd(), value); continue; } if (flag === '--snapshot-in') { result.snapshotIn = privatePath(value, flag); continue; } if (flag === '--snapshot-out') { result.snapshotOut = privatePath(value, flag); continue; } if (flag === '--report-out') { result.reportOut = privatePath(value, flag); continue; } throw new Error(`unsupported argument: ${flag}`); } if (result.snapshotIn && result.snapshotOut) throw new Error('--snapshot-in and --snapshot-out are mutually exclusive'); for (const output of [result.snapshotOut, result.reportOut]) if (output && existsSync(output)) throw new Error(`output exists; refusing to overwrite: ${output}`); return result; }
function fixtures(root: string) { return Object.fromEntries(WAVE_C_STATES.map((state) => [state, JSON.parse(readFileSync(resolve(root, `${state}.json`), 'utf8'))])) as Record<WaveCState, unknown>; }
function snapshot(path: string) { const value = JSON.parse(readFileSync(path, 'utf8')) as { schemaVersion?: number; fixtures?: Record<WaveCState, unknown> }; if (value.schemaVersion !== 1 || !value.fixtures) throw new Error('invalid Wave C offline snapshot'); return value.fixtures; }
function writeNew(path: string, value: unknown) { mkdirSync(privateRoot, { recursive: true }); writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { encoding: 'utf8', flag: 'wx' }); }

const options = parseArgs(process.argv.slice(2)); const source = options.snapshotIn ? snapshot(options.snapshotIn) : fixtures(options.fixtureDir); WAVE_C_STATES.forEach((state) => normalizeWaveCPdfFixture(source[state])); if (options.snapshotOut) writeNew(options.snapshotOut, { schemaVersion: 1, capturedAt: new Date().toISOString(), fixtures: source });
const audit = buildWaveCReport(source); const fetchDiagnostics: Record<string, string> = {}; if (options.fetch) await Promise.all(options.states.map(async (state) => { try { await fetchWaveCPdfProvider(state, source[state]); } catch (error) { fetchDiagnostics[state] = error instanceof Error ? error.message : String(error); } })); if (options.replay) { const replay = buildWaveCReport(source); if (replay.inputDigest !== audit.inputDigest || replay.documentDigest !== audit.documentDigest || replay.evidenceDigest !== audit.evidenceDigest || replay.planDigest !== audit.planDigest) throw new Error('non-deterministic Wave C offline replay'); }
const report = { operation: audit.operation, dryRun: !options.fetch, networkFetchRequested: options.fetch, state: options.states.length === 1 ? options.states[0] : 'all-wave-c', inputDigest: audit.inputDigest, documentDigest: audit.documentDigest, evidenceDigest: audit.evidenceDigest, planDigest: audit.planDigest, counts: audit.counts, states: Object.fromEntries(options.states.map((state) => [state, audit.states[state]])), fetchDiagnostics }; if (options.reportOut) writeNew(options.reportOut, report); console.log(JSON.stringify(report, null, 2));
