import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import process from 'node:process';
import { captureFecFinance, canonicalFinanceCandidates, buildFecFinanceBaselinePlan, validateFecFinanceCaptureSnapshot, type FecFinanceCaptureSnapshot } from './lib/fecFinanceDepth.js';
import { validateResearchMetricsBaselineSnapshot } from './lib/researchMetricsBaseline.js';
import { buildFecFinancePreflight, loadFecApiKey } from './lib/fecFinanceCaptureCli.js';

const privateRoot = resolve(process.cwd(), '.artifacts', 'private', 'canonical-migration');
type Options = { snapshotIn: string; publicationSnapshot?: string; snapshotOut?: string; state?: string; limit: number; maxCalls: number; dryRun: boolean; preflight: boolean; verifyReplay: boolean };
const privatePath = (value: string, flag: string) => { const path = resolve(process.cwd(), value); const child = relative(privateRoot, path); if (!child || child.startsWith('..') || !path.endsWith('.json')) throw new Error(`${flag} must be a .json file beneath .artifacts/private/canonical-migration/`); return path; };
function parse(args: string[]): Options {
  const value: Partial<Options> = { limit: Infinity, maxCalls: 300, dryRun: false, preflight: false, verifyReplay: false };
  for (let index = 0; index < args.length; index += 1) { const flag = args[index]; if (flag === '--dry-run' || flag === '--preflight' || flag === '--verify-replay') { const key = flag === '--dry-run' ? 'dryRun' : flag === '--preflight' ? 'preflight' : 'verifyReplay'; if (value[key]) throw new Error(`duplicate ${flag}`); value[key] = true; continue; } if (!['--snapshot-in', '--publication-snapshot', '--snapshot-out', '--state', '--limit', '--max-calls'].includes(flag)) throw new Error(`unsupported argument: ${flag}`); const item = args[++index]; if (!item || item.startsWith('--')) throw new Error(`missing value for ${flag}`); if (flag === '--snapshot-in') { if (value.snapshotIn) throw new Error('duplicate --snapshot-in'); value.snapshotIn = privatePath(item, flag); } if (flag === '--publication-snapshot') { if (value.publicationSnapshot) throw new Error('duplicate --publication-snapshot'); value.publicationSnapshot = privatePath(item, flag); } if (flag === '--snapshot-out') { if (value.snapshotOut) throw new Error('duplicate --snapshot-out'); value.snapshotOut = privatePath(item, flag); } if (flag === '--state') { if (value.state || !/^[A-Z]{2}$/.test(item)) throw new Error('state must be one uppercase postal abbreviation'); value.state = item; } if (flag === '--limit') value.limit = Number(item); if (flag === '--max-calls') value.maxCalls = Number(item); }
  if (!value.snapshotIn || !Number.isInteger(value.limit) && value.limit !== Infinity || (value.limit as number) <= 0 || !Number.isInteger(value.maxCalls) || (value.maxCalls as number) <= 0 || (value.maxCalls as number) > 300) throw new Error('invalid capture options');
  if (value.dryRun && value.snapshotOut) throw new Error('--dry-run cannot write a capture'); return value as Options;
}
const load = (path: string) => JSON.parse(readFileSync(path, 'utf8')) as unknown;
const writeExclusive = (path: string, value: unknown) => { mkdirSync(privateRoot, { recursive: true }); writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { encoding: 'utf8', flag: 'wx' }); };
const now = () => new Date().toISOString();
async function officialRequest(apiKey: string, path: string, page: number) {
  const separator = path.includes('?') ? '&' : '?'; const response = await fetch(`https://api.open.fec.gov/v1${path}${separator}api_key=${encodeURIComponent(apiKey)}&page=${page}&per_page=100`);
  if (response.status === 429) throw new Error('official FEC API rate limit (429)'); if (!response.ok) throw new Error(`official FEC API response ${response.status}`); const body = await response.json(); if (!body || typeof body !== 'object' || !Array.isArray((body as { results?: unknown }).results)) throw new Error('malformed official FEC response'); return body as { results: unknown[]; pagination?: { pages?: number } };
}
function report(capture: FecFinanceCaptureSnapshot, source: unknown, state?: string) { const first = buildFecFinanceBaselinePlan(source, capture); if (first.financeAudit.orphanRecords || first.audit.orphanDocuments || first.audit.duplicateDocuments || first.audit.leakage) throw new Error('finance merge reference safety check failed'); return { operation: 'offline-fec-finance-replay', dryRun: true, firebaseInitialized: false, state: state ?? capture.state, calls: capture.calls, maxCalls: capture.maxCalls, captureDigest: capture.inputDigest, inputDigest: first.inputDigest, evidenceDigest: first.evidenceDigest, planDigest: first.planDigest, coverage: first.coverage, financeAudit: first.financeAudit }; }

const options = parse(process.argv.slice(2)); if (options.snapshotOut && existsSync(options.snapshotOut)) throw new Error('FEC finance capture output already exists; refusing to overwrite evidence');
const firstInput = load(options.snapshotIn);
if ((firstInput as { schemaVersion?: unknown }).schemaVersion === 1) {
  if (!options.publicationSnapshot) throw new Error('--publication-snapshot is required when --snapshot-in is a finance capture'); const capture = validateFecFinanceCaptureSnapshot(firstInput); const source = validateResearchMetricsBaselineSnapshot(load(options.publicationSnapshot)); if (capture.sourceSnapshotInputDigest !== source.inputDigest) throw new Error('finance capture source snapshot digest mismatch'); const first = report(capture, source, options.state); if (options.verifyReplay) { const second = report(capture, source, options.state); if (JSON.stringify(first) !== JSON.stringify(second)) throw new Error('finance replay is not deterministic'); } console.log(JSON.stringify(first, null, 2));
} else {
  const source = validateResearchMetricsBaselineSnapshot(firstInput); const state = options.state; if (!state) throw new Error('--state is required for a bounded official FEC capture'); const candidates = canonicalFinanceCandidates(source, state).slice(0, options.limit);
  if (options.preflight) { if (!options.snapshotOut) throw new Error('--preflight requires the intended --snapshot-out path'); const ignored = readFileSync('.gitignore', 'utf8').split(/\r?\n/).includes('.artifacts/private/canonical-migration/'); const key = loadFecApiKey(); console.log(JSON.stringify(buildFecFinancePreflight({ sourceSnapshotInputDigest: source.inputDigest, state, candidateCount: candidates.length, maxCalls: options.maxCalls, outputPath: options.snapshotOut, outputExists: existsSync(options.snapshotOut), ignored, key }), null, 2)); }
  else if (options.dryRun) { console.log(JSON.stringify({ operation: 'offline-fec-finance-capture-plan', dryRun: true, firebaseInitialized: false, state, canonicalCandidates: candidates.length, plannedMaximumCalls: candidates.length * 2, maxCalls: options.maxCalls, sourceSnapshotInputDigest: source.inputDigest }, null, 2)); }
  else { loadFecApiKey(); const apiKey = process.env.FEC_API_KEY; if (!apiKey) throw new Error('FEC_API_KEY is required for an official capture.'); const capture = await captureFecFinance({ sourceSnapshotInputDigest: source.inputDigest, capturedAt: now(), state, candidates, limit: candidates.length, maxCalls: options.maxCalls, request: (path, page) => officialRequest(apiKey, path, page) }); if (options.snapshotOut) writeExclusive(options.snapshotOut, capture); const result = report(capture, source, state); if (options.verifyReplay) { const second = report(capture, source, state); if (JSON.stringify(result) !== JSON.stringify(second)) throw new Error('finance capture replay is not deterministic'); } console.log(JSON.stringify({ ...result, operation: 'official-fec-finance-capture' }, null, 2)); }
}
