import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import process from 'node:process';
import dotenv from 'dotenv';
import { FEC_BULK_URL, validateFecBulkFinanceSnapshot } from './lib/fecBulkFinance.js';
import { buildCongressDepthSnapshot, buildCongressResearchPlan, canonicalCongressReferences, matchHouseVote, matchSenateVote, type CongressCandidateCapture, type CongressLegislation, type CongressProfile, type CongressVote, validateCongressDepthSnapshot } from './lib/congressDepth.js';
import { normalizeVoteCast, parseSenateVoteMenu, parseSenateVoteXml } from './lib/rollCalls.js';

const root = resolve(process.cwd(), '.artifacts', 'private', 'canonical-migration'); const api = 'https://api.congress.gov/v3';
const privatePath = (value: string, flag: string, suffix: string) => { const path = resolve(process.cwd(), value); const child = relative(root, path); if (!child || child.startsWith('..') || !path.endsWith(suffix)) throw new Error(`${flag} must be beneath .artifacts/private/canonical-migration/`); return path; };
type Options = { snapshotIn: string; financeSnapshot: string; publicationSnapshot?: string; snapshotOut?: string; checkpointDir?: string; preflight: boolean; resume: boolean; verify: boolean; maxCalls: number };
function args(argv: string[]): Options { const value: Partial<Options> = { preflight: false, resume: false, verify: false, maxCalls: 1600 }; for (let index = 0; index < argv.length; index += 1) { const flag = argv[index]!; if (flag === '--preflight' || flag === '--resume' || flag === '--verify-replay') { const key = flag === '--verify-replay' ? 'verify' : flag === '--preflight' ? 'preflight' : 'resume'; if (value[key]) throw new Error(`duplicate ${flag}`); value[key] = true; continue; } if (!['--snapshot-in','--finance-snapshot','--publication-snapshot','--snapshot-out','--checkpoint-dir','--max-calls'].includes(flag)) throw new Error(`unsupported ${flag}`); const item = argv[++index]; if (!item || item.startsWith('--')) throw new Error(`missing ${flag}`); if (flag === '--snapshot-in') value.snapshotIn = privatePath(item, flag, '.json'); if (flag === '--finance-snapshot') value.financeSnapshot = privatePath(item, flag, '.json'); if (flag === '--publication-snapshot') value.publicationSnapshot = privatePath(item, flag, '.json'); if (flag === '--snapshot-out') value.snapshotOut = privatePath(item, flag, '.json'); if (flag === '--checkpoint-dir') value.checkpointDir = privatePath(item, flag, ''); if (flag === '--max-calls') value.maxCalls = Number(item); } if (!value.snapshotIn || !value.financeSnapshot || !Number.isInteger(value.maxCalls) || value.maxCalls! < 1 || value.maxCalls! > 1600) throw new Error('requires private snapshots and --max-calls 1..1600'); if (!value.preflight && !value.publicationSnapshot && !value.snapshotOut) throw new Error('capture requires --snapshot-out'); if (value.snapshotOut && existsSync(value.snapshotOut)) throw new Error('snapshot output already exists; refusing overwrite'); return value as Options; }
const write = (path: string, value: unknown) => { mkdirSync(resolve(path, '..'), { recursive: true }); writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx' }); };
function normalizeBills(value: unknown): CongressLegislation[] { const bills = Array.isArray((value as any)?.sponsoredLegislation) ? (value as any).sponsoredLegislation : Array.isArray((value as any)?.cosponsoredLegislation) ? (value as any).cosponsoredLegislation : []; return bills.map((bill: any) => ({ identifier: bill.type && bill.number ? `${String(bill.type).toUpperCase()} ${bill.number}` : 'unknown', title: String(bill.title ?? ''), introducedDate: bill.introducedDate ?? null, latestAction: { text: bill.latestAction?.text ?? null, date: bill.latestAction?.actionDate ?? null }, sourceUrl: bill.url ?? '' })).filter((bill: CongressLegislation) => bill.identifier !== 'unknown' && bill.title && /^https:\/\/api\.congress\.gov\//.test(bill.sourceUrl)); }
function normalizeProfile(value: any, bioguideId: string, retrievedAt: string): CongressProfile | null { const member = value?.member; const chamber = (input: unknown) => /senate/i.test(String(input)) ? 'Senate' as const : /house/i.test(String(input)) ? 'House' as const : null; const terms = Array.isArray(member?.terms) ? member.terms.map((term: any) => ({ chamber: chamber(term.chamber), state: String(term.stateCode ?? term.stateName ?? member.state ?? ''), district: term.district == null ? null : String(term.district), startYear: Number.isInteger(term.startYear) ? term.startYear : null, endYear: Number.isInteger(term.endYear) ? term.endYear : null })).filter((term: any): term is CongressProfile['terms'][number] => term.chamber !== null) : []; if (!member || !terms.length) return null; const current = terms[terms.length - 1]!; return { chamber: current.chamber, state: current.state, district: current.district, partyHistory: Array.isArray(member.partyHistory) ? member.partyHistory.map((party: any) => ({ party: String(party.partyName ?? ''), startYear: Number.isInteger(party.startYear) ? party.startYear : null })) : [], terms, officialName: String(member.directOrderName ?? bioguideId), sourceUrl: `https://api.congress.gov/v3/member/${bioguideId}`, retrievedAt }; }
const options = args(process.argv.slice(2)); dotenv.config({ path: resolve(process.cwd(), '.env.local'), override: false, quiet: true });
const finance = validateFecBulkFinanceSnapshot(JSON.parse(readFileSync(options.financeSnapshot, 'utf8')));
if (options.publicationSnapshot) { const publication = JSON.parse(readFileSync(options.publicationSnapshot, 'utf8')); const capture = validateCongressDepthSnapshot(JSON.parse(readFileSync(options.snapshotIn, 'utf8'))); const plan = buildCongressResearchPlan(publication, finance, capture); const report = { operation: 'offline-congress-depth-replay', dryRun: true, firebaseInitialized: false, congressApiCalls: 0, senateApiCalls: 0, sourceDigest: capture.inputDigest, inputDigest: plan.inputDigest, evidenceDigest: plan.evidenceDigest, planDigest: plan.planDigest, coverage: plan.congressCoverage }; if (options.verify && JSON.stringify(report) !== JSON.stringify({ ...report })) throw new Error('nondeterministic replay'); console.log(JSON.stringify(report, null, 2)); }
else { const publication = JSON.parse(readFileSync(options.snapshotIn, 'utf8')); const refs = canonicalCongressReferences(publication); if (options.preflight) { console.log(JSON.stringify({ operation: 'congress-depth-preflight', dryRun: true, congressApi: api, senateApi: 'https://www.senate.gov', apiKeyPresent: Boolean(process.env.CONGRESS_GOV_API_KEY), canonicalBioguideReferences: [...refs.values()].reduce((sum, values) => sum + values.length, 0), uniqueBioguideIds: refs.size, maxCalls: options.maxCalls, snapshotOut: options.snapshotOut ?? null, pathsPrivate: true, pathsIgnored: readFileSync('.gitignore','utf8').includes('.artifacts/private/canonical-migration/'), firebaseInitialized: false }, null, 2)); } else {
  if (!options.checkpointDir || !process.env.CONGRESS_GOV_API_KEY) throw new Error('capture requires --checkpoint-dir and CONGRESS_GOV_API_KEY');
  let calls = 0; const checkpoint = (key: string) => resolve(options.checkpointDir!, `${key.replace(/[^A-Za-z0-9_.-]/g, '_')}.json`);
  const request = async (key: string, sourceUrl: string, parser: 'json' | 'text', requestUrl = sourceUrl) => { const path = checkpoint(key); if (existsSync(path)) { if (!options.resume) throw new Error(`checkpoint already exists; rerun only with --resume: ${key}`); const saved = JSON.parse(readFileSync(path,'utf8')); if (saved?.schemaVersion !== 1 || saved?.sourceUrl !== sourceUrl || typeof saved?.body !== 'string') throw new Error(`invalid checkpoint: ${key}`); return saved.body; } let failure: unknown; for (let attempt = 1; attempt <= 3; attempt += 1) { try { if (calls >= options.maxCalls) throw new Error(`Congress depth call budget exhausted at ${calls}/${options.maxCalls}`); calls += 1; const response = await fetch(requestUrl); if (response.status === 404) { const body = ''; write(path, { schemaVersion: 1, sourceUrl, parser, body }); return body; } if (!response.ok) { const retryAfter = Math.min(30, Number(response.headers.get('retry-after')) || 0); if (![429, 500, 502, 503, 504].includes(response.status)) throw new Error(`official source HTTP ${response.status}`); if (attempt === 3) throw new Error(`official source HTTP ${response.status} after ${attempt} attempts`); if (retryAfter) await new Promise((done) => setTimeout(done, retryAfter * 1000)); else await new Promise((done) => setTimeout(done, 300 * attempt)); continue; } const body = parser === 'json' ? JSON.stringify(await response.json()) : await response.text(); write(path, { schemaVersion: 1, sourceUrl, parser, body }); await new Promise((done) => setTimeout(done, 80)); return body; } catch (error) { failure = error; if (String(error).includes('HTTP ') || String(error).includes('budget') || attempt === 3) break; await new Promise((done) => setTimeout(done, 300 * attempt)); } } throw failure; };
  const congress = (key: string, path: string) => { const sourceUrl = `${api}${path}`; const requestUrl = `${sourceUrl}${path.includes('?') ? '&' : '?'}format=json&api_key=${encodeURIComponent(process.env.CONGRESS_GOV_API_KEY!)}`; return request(key, sourceUrl, 'json', requestUrl); };
  const captures: CongressCandidateCapture[] = [];
  for (const [bioguideId, references] of refs) { const profileText = await congress(`member-${bioguideId}`, `/member/${bioguideId}`); const sponsoredText = profileText ? await congress(`sponsored-${bioguideId}`, `/member/${bioguideId}/sponsored-legislation?limit=5`) : ''; const cosponsoredText = profileText ? await congress(`cosponsored-${bioguideId}`, `/member/${bioguideId}/cosponsored-legislation?limit=5`) : ''; const capturedAt = new Date().toISOString(); const profile = profileText ? normalizeProfile(JSON.parse(profileText), bioguideId, capturedAt) : null; captures.push({ bioguideId, references, status: profile ? 'present' : 'unavailable', ...(profile ? { profile } : { failureReason: 'No official Congress.gov member profile was returned.' }), sponsored: sponsoredText ? normalizeBills(JSON.parse(sponsoredText)) : [], cosponsored: cosponsoredText ? normalizeBills(JSON.parse(cosponsoredText)) : [], votes: [] }); }
  const houseList = JSON.parse(await congress('house-list-119-2', '/house-vote/119/2?limit=20')); const houseRows = Array.isArray(houseList.houseRollCallVotes) ? houseList.houseRollCallVotes.slice(0,20) : []; const houseVotes: Array<{ rollNumber: number; date: string; title: string | null; question: string | null; result: string | null; sourceUrl: string; members: any[] }> = [];
  for (const row of houseRows) { const number = Number(row.rollCallNumber); const sourceUrl = `${api}/house-vote/119/2/${number}/members`; const detail = JSON.parse(await congress(`house-${number}`, `/house-vote/119/2/${number}/members?limit=500`)); houseVotes.push({ rollNumber: number, date: String(row.startDate ?? ''), title: row.voteType ?? null, question: row.legislationType && row.legislationNumber ? `${row.legislationType} ${row.legislationNumber}` : null, result: row.result ?? null, sourceUrl, members: detail.houseRollCallVoteMemberVotes?.results ?? [] }); }
  const senateMenuUrl = 'https://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_119_2.xml'; const senateMenu = parseSenateVoteMenu(await request('senate-menu-119-2', senateMenuUrl, 'text')).slice(0,20); const senateVotes = [] as ReturnType<typeof parseSenateVoteXml>[];
  for (const item of senateMenu) { const padded = String(item.rollNumber).padStart(5,'0'); const sourceUrl = `https://www.senate.gov/legislative/LIS/roll_call_votes/vote1192/vote_119_2_${padded}.xml`; senateVotes.push(parseSenateVoteXml(await request(`senate-${padded}`, sourceUrl, 'text'), sourceUrl)); }
  for (const captured of captures) if (captured.profile) { for (const vote of houseVotes) if (captured.references.some((reference) => reference.chamber === 'House')) { const member = vote.members.find((item) => matchHouseVote({ bioguideId: item.bioguideID }, captured.bioguideId)); const cast = normalizeVoteCast(member?.voteCast); if (cast) captured.votes.push({ chamber: 'House', congress: 119, session: 2, rollNumber: vote.rollNumber, date: vote.date, question: vote.question, title: vote.title, result: vote.result, vote: cast, sourceUrl: vote.sourceUrl, matchingMethod: 'bioguide-exact' }); } for (const vote of senateVotes) if (captured.references.some((reference) => reference.chamber === 'Senate')) { const matched = matchSenateVote(vote.members, { officialName: captured.profile.officialName, state: captured.profile.state }); const cast = matched.status === 'matched' ? normalizeVoteCast(matched.member.voteCast) : null; if (cast) captured.votes.push({ chamber: 'Senate', congress: 119, session: 2, rollNumber: vote.rollNumber, date: vote.date ?? '', question: vote.question ?? null, title: vote.title ?? null, result: vote.result ?? null, vote: cast, sourceUrl: vote.sourceUrl, matchingMethod: 'senate-name-state-exact' }); } }
  const capturedAt = new Date().toISOString(); const final = buildCongressDepthSnapshot({ source: { publicationInputDigest: (publication as any).inputDigest, financeInputDigest: finance.inputDigest, capturedAt }, maxCalls: options.maxCalls, calls, candidates: captures, rollCalls: [...houseVotes.map((vote) => ({ chamber: 'House' as const, congress: 119 as const, session: 2 as const, rollNumber: vote.rollNumber, sourceUrl: vote.sourceUrl })), ...senateVotes.map((vote) => ({ chamber: 'Senate' as const, congress: 119 as const, session: 2 as const, rollNumber: vote.rollNumber, sourceUrl: vote.sourceUrl }))] }); const plan = buildCongressResearchPlan(publication, finance, final); if (options.verify && JSON.stringify(plan) !== JSON.stringify(buildCongressResearchPlan(publication, finance, final))) throw new Error('nondeterministic Congress depth plan'); write(options.snapshotOut!, final); console.log(JSON.stringify({ operation: 'official-congress-depth-capture', firebaseInitialized: false, congressApiCalls: calls, senateApiCalls: senateVotes.length + 1, checkpointCount: calls, sourceDigest: final.inputDigest, inputDigest: plan.inputDigest, evidenceDigest: plan.evidenceDigest, planDigest: plan.planDigest, coverage: plan.congressCoverage }, null, 2));
} }
